enum MovieGenreEnum {
  ACAO = 'AÇÃO',
  ANIMACAO = 'ANIMAÇÃO',
  AVENTURA = 'AVENTURA',
  COMEDIA = 'COMÉDIA',
  DOCUMENTARIO = 'DOCUMENTÁRIO',
  DRAMA = 'DRAMA',
  FANTASIA = 'FANTASIA',
  FICCAO = 'FICÇÃO',
  MUSICAL = 'MUSICAL',
  ROMANCE = 'ROMANCE',
  SUSPENSE = 'SUSPENSE',
  TERROR = 'TERROR',
  BIOGRAFIA = 'BIOGRAFIA',
  OUTRO = 'OUTRO'
}

enum MovieReviewEnum{
  PESSIMO='PESSIMO',
  RUIM='RUIM',
  REGULAR='REGULAR',
  BOM='BOM',
  MUITO_BOM='MUITO BOM',
  EXCELENTE='EXCELENTE'
}

export {MovieGenreEnum, MovieReviewEnum}