export enum MovieGenreEnum {
  ACAO = 'AÇÃO',
  ANIMACAO = 'ANIMAÇÃO',
  AVENTURA = 'AVENTURA',
  COMEDIA = 'COMÉDIA',
  DOCUMENTARIO = 'DOCUMENTÁRIO',
  DRAMA = 'DRAMA',
  FANTASIA = 'FANTASIA',
  FICCAO = 'FICÇÃO',
  MUSICAL = 'MUSICAL',
  ROMANCE = 'ROMANCE',
  SUSPENSE = 'SUSPENSE',
  TERROR = 'TERROR',
  BIOGRAFIA = 'BIOGRAFIA',
  OUTRO = 'OUTRO'
}